import { render, screen } from "@testing-library/react";
import ThemeDetailContent from "./ThemeDetailContent";
import { MarketTheme } from "@/types";

vi.mock("next/link", () => ({
  default: ({
    children,
    href,
    className,
  }: {
    children: React.ReactNode;
    href: string;
    className?: string;
  }) => (
    <a href={href} className={className}>
      {children}
    </a>
  ),
}));

vi.mock("./NewsCard", () => ({
  default: ({ news }: { news: { id: string; headline: string } }) => (
    <article data-testid="news-card" data-news-id={news.id}>
      {news.headline}
    </article>
  ),
}));

vi.mock("./SentimentBadge", () => ({
  default: ({ sentiment }: { sentiment: string }) => (
    <span data-testid="sentiment-badge">{sentiment.toUpperCase()}</span>
  ),
}));

const ARTICLE_1 = {
  id: "art-001",
  headline: "Fed signals rate cut in September",
  summary: "Fed summary",
  source_url: null,
  content: "content",
  category: "ดอกเบี้ยโลก" as const,
  published_at: "2025-06-05T10:00:00Z",
  source: "Reuters",
  ai_analysis: null,
  stock_impacts: [],
  featured: false,
};

const ARTICLE_2 = {
  id: "art-002",
  headline: "Banking stocks rally on rate cut hopes",
  summary: "Banking summary",
  source_url: null,
  content: "content",
  category: "หุ้นไทย" as const,
  published_at: "2025-06-01T08:00:00Z",
  source: "Bloomberg",
  ai_analysis: null,
  stock_impacts: [],
  featured: false,
};

const VALID_THEME: MarketTheme = {
  theme_id: "theme-001",
  name: "Fed Rate Cut Sentiment",
  description:
    "Markets anticipate rate cuts following softer CPI data. Banking stocks price in 2 cuts by year-end. SET banking sector outperforms.",
  overall_sentiment: "bullish",
  article_count: 2,
  last_article_at: "2025-06-05T10:00:00Z",
  created_at: "2025-06-01T00:00:00Z",
  constituent_articles: [ARTICLE_1, ARTICLE_2],
};

describe("ThemeDetailContent", () => {
  it("renders theme name as h1", () => {
    render(<ThemeDetailContent theme={VALID_THEME} />);
    const heading = screen.getByRole("heading", { level: 1 });
    expect(heading).toHaveTextContent("Fed Rate Cut Sentiment");
  });

  it("renders SentimentBadge", () => {
    render(<ThemeDetailContent theme={VALID_THEME} />);
    expect(screen.getByTestId("sentiment-badge")).toBeInTheDocument();
    expect(screen.getByTestId("sentiment-badge")).toHaveTextContent("BULLISH");
  });

  it("renders article count", () => {
    render(<ThemeDetailContent theme={VALID_THEME} />);
    expect(screen.getByText(/2 articles/)).toBeInTheDocument();
  });

  it("renders date range derived from constituent articles", () => {
    render(<ThemeDetailContent theme={VALID_THEME} />);
    expect(screen.getByText(/Jun 1, 2025/)).toBeInTheDocument();
    expect(screen.getByText(/Jun 5, 2025/)).toBeInTheDocument();
  });

  it("renders theme description", () => {
    render(<ThemeDetailContent theme={VALID_THEME} />);
    expect(
      screen.getByText(/Markets anticipate rate cuts/)
    ).toBeInTheDocument();
  });

  it("renders one NewsCard per constituent article", () => {
    render(<ThemeDetailContent theme={VALID_THEME} />);
    const cards = screen.getAllByTestId("news-card");
    expect(cards).toHaveLength(2);
  });

  it("renders the non-removable AI disclaimer", () => {
    render(<ThemeDetailContent theme={VALID_THEME} />);
    expect(
      screen.getByText(
        /This analysis is generated by AI for educational purposes only/
      )
    ).toBeInTheDocument();
  });

  it("uses singular 'article' when article_count is 1", () => {
    render(
      <ThemeDetailContent
        theme={{ ...VALID_THEME, article_count: 1 }}
      />
    );
    expect(screen.getByText(/1 article[^s]/)).toBeInTheDocument();
  });

  it("shows empty state when constituent_articles is empty", () => {
    render(
      <ThemeDetailContent
        theme={{ ...VALID_THEME, constituent_articles: [] }}
      />
    );
    expect(
      screen.getByText("No articles available for this theme.")
    ).toBeInTheDocument();
  });
});
