import { MarketTheme, NewsItem } from "@/types";
import NewsCard from "./NewsCard";
import SentimentBadge from "./SentimentBadge";

function dateRange(articles: NewsItem[]): string {
  if (articles.length === 0) return "";
  const times = articles.map((a) => new Date(a.published_at).getTime());
  const oldest = new Date(Math.min(...times));
  const newest = new Date(Math.max(...times));
  const fmt = (d: Date) =>
    d.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  return oldest.getTime() === newest.getTime()
    ? fmt(oldest)
    : `${fmt(oldest)} – ${fmt(newest)}`;
}

interface Props {
  theme: MarketTheme;
}

export default function ThemeDetailContent({ theme }: Props) {
  const range = dateRange(theme.constituent_articles);

  return (
    <article className="space-y-4">
      {/* Zone 1: Theme name + SentimentBadge */}
      <div className="flex items-start gap-3">
        <h1
          className="text-xl font-bold leading-snug flex-1"
          style={{ color: "#4A342A" }}
        >
          {theme.name}
        </h1>
        <div className="flex-shrink-0 mt-0.5">
          <SentimentBadge sentiment={theme.overall_sentiment} />
        </div>
      </div>

      {/* Zone 2: Article count + date range */}
      <p className="text-sm" style={{ color: "#7D5A44" }}>
        {theme.article_count}{" "}
        {theme.article_count === 1 ? "article" : "articles"}
        {range ? ` · ${range}` : ""}
      </p>

      {/* Zone 3: Description */}
      <p className="text-sm leading-relaxed" style={{ color: "#7D5A44" }}>
        {theme.description}
      </p>

      {/* Zone 4: Constituent articles */}
      {theme.constituent_articles.length === 0 ? (
        <p className="text-sm" style={{ color: "#6b6560" }}>
          No articles available for this theme.
        </p>
      ) : (
        <div className="space-y-4">
          {[...theme.constituent_articles]
            .sort(
              (a, b) =>
                new Date(b.published_at).getTime() -
                new Date(a.published_at).getTime()
            )
            .map((article) => (
              <NewsCard key={article.id} news={article} />
            ))}
        </div>
      )}

      {/* Zone 5: Non-removable AI disclaimer — FR-A04 */}
      <div
        className="pt-4 border-t text-xs leading-relaxed"
        style={{ borderColor: "rgba(74,52,42,0.1)", color: "#6b6560" }}
      >
        This analysis is generated by AI for educational purposes only. It does
        not constitute investment advice. Always consult a qualified financial
        advisor before making investment decisions.
      </div>
    </article>
  );
}
